//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerInput) DeepCopyInto(out *ServerInput) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerInput.
func (in *ServerInput) DeepCopy() *ServerInput {
	if in == nil {
		return nil
	}
	out := new(ServerInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServerInput) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerInputSpec) DeepCopyInto(out *ServerInputSpec) {
	*out = *in
	in.Input.DeepCopyInto(&out.Input)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerInputSpec.
func (in *ServerInputSpec) DeepCopy() *ServerInputSpec {
	if in == nil {
		return nil
	}
	out := new(ServerInputSpec)
	in.DeepCopyInto(out)
	return out
}
